services:
  nestjs_api: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=dinhhuuphat
      - MYSQL_DATABASE=nestjs_mysql
      - MYSQL_USER=dinhhuuphat
      - MYSQL_PASSWORD=dinhhuuphat
      - MYSQL_TCP_PORT=3307
    
      
